development: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bicycle_development
  username: postgres
  password: "12345"
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: bicycle_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: bicycle_production
